# Generated by Django 5.1.2 on 2024-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackerAndMover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('local_move_cost_range', models.CharField(max_length=100)),
                ('intercity_move_cost_range', models.CharField(max_length=100)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reviews_count', models.IntegerField()),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
